version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile: OIDC-USER
                role_arn: arn:aws:iam::538253826620:role/video-tagger-circleci-pusher
          region: ap-southeast-2

          repo: public.ecr.aws/d4n8a6t5/video-tagger-api
          tag: ${CIRCLE_SHA1}
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                profile: OIDC-USER
                role_arn: arn:aws:iam::538253826620:role/video-tagger-circleci-pusher
          cluster: video-tagger
          container_image_name_updates: container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}
          family: ${MY_APP_PREFIX}-service
          requires:
            - aws-ecr/build_and_push_image
