version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::538253826620:role/video-tagger-circleci-pusher
          cluster: video-tagger
          container_image_name_updates: container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}
          family: ${MY_APP_PREFIX}-service
          requires:
            - build-and-push-image

jobs:
  build-and-push-image:
    docker:
      - image: circleci/python:3.8  # or any Docker image that suits your needs
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Write ENV VAR to file
          command: echo $GCP_KEY > /app/key.json
      - run:
          name: Build Docker image
          command: docker build -t ${MY_APP_PREFIX}:${CIRCLE_SHA1} .
      - aws-cli/setup:
          role_arn: arn:aws:iam::538253826620:role/video-tagger-circleci-pusher
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin public.ecr.aws/d4n8a6t5
      - run:
          name: Tag Docker image
          command: docker tag ${MY_APP_PREFIX}:${CIRCLE_SHA1} public.ecr.aws/d4n8a6t5/video-tagger-api:${CIRCLE_SHA1}
      - run:
          name: Push Docker image to ECR
          command: docker push public.ecr.aws/d4n8a6t5/video-tagger-api:${CIRCLE_SHA1}
